version: '2'
services:

    instance1-vsftpd:
      build: .
      container_name: instance1-vsftpd
      environment:
        - FTP_PASS=$$5$$mDcjdVJpbdsVcP0h$$PGXb4.fi25eXkuod5PxZ0nX1FfMHpjo8ynt5TxCw8mD
        - ONLY_UPLOAD=NO
        - ONLY_DOWNLOAD=NO
        - MAX_CLIENTS=100
        - MAX_PER_IP=50
        - LISTEN_IPV6=no
        - SECCOMP_SANDBOX=NO
        - ANONYMOUS_ENABLE=NO
        - PASV_ENABLE=YES
        - PASV_ADDRESS=127.0.0.1
        - PASV_MIN=21200
        - PASV_MAX=21210
      depends_on:
        - instance1-vsftpd-data
      volumes_from:
        - instance1-vsftpd-data
      ports:
        - "8021:21"
        - "21200-21210:21200-21210"

    instance1-vsftpd-data:
      image: busybox
      container_name: instance1-vsftpd-data
      volumes:
        - /tmp:/home
